### ISSUE TITLE
setup Github site w/ issues, milestones and project

### ISSUE THREAD

**Issue by bbest** [ecoquants/nrel-cables#10]

**Comment by bbest** [comment]
Hi @lkilcher,

I setup the Github repository [ecoquants/nrel-cables](https://github.com/ecoquants/nrel-cables/issues/10) for project management. I invited you as a Collaborator with Admin privileges. Please accept this invitation:

https://github.com/ecoquants/nrel-cables/invitations

Working from Timeline and detailed Tasks in Statement of Work (SoW), we now have in Github:

- [**Issues**](https://github.com/ecoquants/nrel-cables/issues): tasks

- [**Milestones**](https://github.com/ecoquants/nrel-cables/milestones?direction=asc&sort=due_date&state=open): associate issues with a deadline

- [**Project**](https://github.com/ecoquants/nrel-cables/projects/1)

Progress and notes for this project are best tracked through issues. See also: [Mastering Issues · GitHub Guides](https://guides.github.com/features/issues/).

## Timeline in SoW

![image](https://cloud.githubusercontent.com/assets/2837257/22989935/73d74ea0-f36c-11e6-94fc-95bb0e5d77d7.png)

## Issues

- [**Issues**](https://github.com/ecoquants/nrel-cables/issues): tasks

![image](https://cloud.githubusercontent.com/assets/2837257/22989884/5191bda8-f36c-11e6-9e89-7ca1e72da004.png)

## Milestones

- [**Milestones**](https://github.com/ecoquants/nrel-cables/milestones?direction=asc&sort=due_date&state=open): associate issues with a deadline

![image](https://cloud.githubusercontent.com/assets/2837257/22990077/e382c82e-f36c-11e6-8db0-e0161c5fe63b.png)

## Project

- [**Project**](https://github.com/ecoquants/nrel-cables/projects/1)

[Github projects](https://help.github.com/articles/about-projects/) are [new Kanban style](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) of managing issues and quick todos.

![image](https://cloud.githubusercontent.com/assets/2837257/22990116/02fef858-f36d-11e6-99da-5bb6628c2409.png)

**Comment by lkilcher** [comment]
Looks great! The contracting office has asked me to make some changes to the SOW. I'm working on getting those done today or tomorrow. Thanks for setting this all up!

**Comment by bbest** [comment]
Sounds good! Will proceed 👍
