### ISSUE TITLE
setup Rmarkdown doc w/ Zotero refs to output: pdf, docx, html

### ISSUE THREAD

**Issue by bbest** [ecoquants/nrel-cables#11]
Similar to [bbest/rmarkdown-example](https://github.com/bbest/rmarkdown-example#writing-with-rmarkdown), setup report as Rmarkdown to weave R chunks with markdown text and output to:

- **pdf**: portable document format for pretty professional static form

- **docx**:  Microsoft Word doc for sharing with collaborators who can use Track Changes for providing feedback

- **html**: online report and view, with ability to follow links and incorporate interactive JS [htmlwidgets](http://www.htmlwidgets.org/), hosted using [Github Pages](https://pages.github.com)

For more on Rmarkdown, see:

- [What is R Markdown? on Vimeo](https://vimeo.com/178485416) 1 min video

- [rmarkdown.rstudio.com](http://rmarkdown.rstudio.com) documentation

**Comment by bbest** [comment]
Hi @lkilcher,

Here's a working report.html/docx/pdf at http://ecoquants.com/nrel-cables with interactive leaflet map in HTML: 

![image](https://cloud.githubusercontent.com/assets/2837257/22999995/4f64d0a2-f393-11e6-8215-e909b32306c0.png)

Zotero references in group library https://www.zotero.org/groups/nrel-cables/items:

![image](https://cloud.githubusercontent.com/assets/2837257/23000044/8d039538-f393-11e6-88e2-5626e54a4d94.png)

**Comment by lkilcher** [comment]
This all looks awesome! I don't have additional references at this time.
Great to have that started.
