### ISSUE TITLE
3. Collect spatial data

### ISSUE THREAD

**Issue by bbest** [ecoquants/nrel-cables#3]
Collect best available spatial data, similar to the U.S. west coast preliminary work:

Data | Source | Website
-----|---------|--------
Offshore Cables | National Oceanic and Atmospheric Administration (NOAA) | http://marinecadastre.gov/data/
Bathymetry | General Bathymetric Chart of the Oceans (GEBCO) | http://www.gebco.net/data_and_products/gridded_bathymetry_data/
U.S. Shoreline | NOAA | http://shoreline.noaa.gov/data/datasheets/medres.html
Tide | Georgia Tech Research Corporation | http://www1.eere.energy.gov/water/pdfs/1023527.pdf
Wave | Electric Power Research Institute | http://www1.eere.energy.gov/water/pdfs/mappingandassessment.pdf
Wind (100m height) | AWS Truepower, LLC for windNavigator® | http://apps2.eere.energy.gov/wind/windexchange/windmaps/

Newer renewable energy datasets from NREL may be provided.

**Comment by bbest** [comment]
HI @lkilcher,

Can you please point me to the latest GIS-friendly download of these NREL datasets to characterize renewable energy potential in the report (at varying levels of constraints)?

Data | Source | Website
-----|---------|--------
Tide | Georgia Tech Research Corporation | http://www1.eere.energy.gov/water/pdfs/1023527.pdf
Wave | Electric Power Research Institute | http://www1.eere.energy.gov/water/pdfs/mappingandassessment.pdf
Wind | AWS Truepower, LLC for windNavigator® | http://apps2.eere.energy.gov/wind/windexchange/windmaps/

The above links point to PDFs and not full downloads. Do you recommend the following NREL data sources for characterizing different marine renewable energy potentials?

## NREL GIS Data - Marine & Hydrokinetic Data

[nrel.gov/gis/data_mhk.html](http://www.nrel.gov/gis/data_mhk.html)

**Download Data** 
Geographic coordinate system name: GCS_WGS_1984

Coverage | Zipped Shapefiles | Last Updated | Metadata
----------|--------------------|--------------|----------
Wave Power Density | [Zip 3.4 MB](http://en.openei.org/datasets/files/868/pub/wave_power_density.zip) | 10/20/2011 | [Wave Power Density.xml](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/International/metadata/wave_power_density.xml)
Wave Energy Period | [Zip 2.4 MB](http://en.openei.org/datasets/files/868/pub/wave_energy_period.zip) | 10/20/2011 | [Wave Energy Period.xml](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/International/metadata/wave_energy_period.xml)
Significant Wave Height | [Zip 2.3 MB](http://en.openei.org/datasets/files/868/pub/wave_significant_height.zip) | 10/20/2011 | [Wave Significant Height.xml](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/International/metadata/wave_significant_height.xml)
Wave Hindcast | [Zip 1.4 MB](http://en.openei.org/datasets/files/868/pub/wave_hindcast_direction.zip) | 10/20/2011 | [Wave Hindcast.xml](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/International/metadata/wave_hindcast.xml)
Wave Study Depth | [Zip 100.8 KB](http://en.openei.org/datasets/files/868/pub/wave_depth.zip) | 10/20/2011 | [Wave Depth.xml](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/International/metadata/wave_depth.xml)

Access the full technical report here: [Mapping and Assessment of the United States Ocean Wave Energy Resource](http://en.openei.org/datasets/node/884).

## NREL GIS Data - Wind Data

[nrel.gov/gis/data_wind.html](http://www.nrel.gov/gis/data_wind.html)

**90-Meter Offshore (90-meter height above surface)**
Annual average offshore wind speed at a 90-meter height. To learn more, please see Offshore Wind Report (2010)PDF.

**Geographic coordinate system name: GCS_WGS_1984**
For these five datasets, we've included the option to view the data in Google Earth. To launch this capability, click on the kmz link in the KMZ Files field. Other KMZ links are available through our MapSearch Tool.

Coverage | Zipped Shapefiles | Last Updated | Metadata | KMZ Files
---------|-------------------|--------------|----------|----------
Atlantic Coast 90m Windspeed Offshore Wind | [Zip 19.7. MB](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/90m/Atlantic_Coast_90m_Windspeed_Offshore_Wind_90m.zip) | 06/26/2012 | [Atlantic Coast.htm](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/metadata/atlantic_coast_metadata.htm) | [Atlantic Coast 90m.kmz](http://mapservices.nrel.gov/data_res/wms/kml?layers=data_res:atlantic_coast_90mwindspeed_off)
Great Lakes 90m Windspeed Offshore Wind | [Zip 11.8 MB](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/90m/Great_Lakes_90mwindspeed_offshore_Wind_90m.zip) | 08/23/2010 | [Great Lakes.htm](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/metadata/great_lakes_metadata.htm) | [Great Lakes 90m.kmz](http://mapservices.nrel.gov/data_res/wms/kml?layers=data_res:great_lakes_90mwindspeed_off)
Gulf of Mexico 90m Windspeed Offshore Wind | [Zip 4.8 MB](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/90m/Gulf_of_Mexico_90mwindspeed_offshore_Wind_90m.zip) | 08/23/2010 | [Gulf of Mexico.htm](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/metadata/gulf_of_mexico_metadata.htm) | [Gulf of Mexico 90m.kmz](http://mapservices.nrel.gov/data_res/wms/kml?layers=data_res:gulf_of_mexico_90mwindspeed_off)
Hawaii 90m Windspeed Offshore Wind | [Zip 4.2 MB](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/90m/Hawaii_90mwindspeed_offshore_Wind_90m.zip) | 08/23/2010 | [Hawaii.htm](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/metadata/90m_hawaii_metadata.htm) | [Hawaii 90m.kmz](http://mapservices.nrel.gov/data_res/wms/kml?layers=data_res:90mwindspeed_hi)
Pacific Coast 90m Windspeed Offshore Wind | [Zip 9.4 MB](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/90m/Pacific_Coast_90mwindspeed_offshore_Wind_90m.zip) | 08/23/2010 | [Pacific Coast.htm](http://www.nrel.gov/gis/data/GIS_Data_Technology_Specific/United_States/Wind/metadata/pacific_coast_90mwindspeed_off.htm) | [Pacific Coast 90m.kmz](http://mapservices.nrel.gov/data_res/wms/kml?layers=data_res:pacific_coast_90mwindspeed_off)

## NREL GIS Tools

[nrel.gov/gis/tools.html](http://www.nrel.gov/gis/tools.html)

Some of these tools point to more refined or alternate data sets.

### Wind Prospector

https://maps.nrel.gov/wind-prospector

#### Wind Power Class (Exclusions Applied)

![image](https://cloud.githubusercontent.com/assets/2837257/24872375/1d546a5a-1dd2-11e7-9a33-e317d8f3965a.png)

> This layer represents the annual average wind resource data used in the Renewable Electricity Futures Study (http://www.nrel.gov/analysis/re_futures)... Standard exclusions were applied to eliminate protected areas (wilderness, wildlife refuges, parks, etc.), incompatible land use (wetlands, urban areas), and other criteria from the available wind resource.

#### Pacific Monthly Offshore Wind Speed

Annual, Jan - Dec

#### Site Analysis

- Species Extent
- Military Boundaries

![image](https://cloud.githubusercontent.com/assets/2837257/24872625/df2d9bd8-1dd2-11e7-96ab-1f1f809beaca.png)

### MHK Atlas

https://maps.nrel.gov/mhk-atlas/

This never finished Loading for me

![image](https://cloud.githubusercontent.com/assets/2837257/24872710/2db23c50-1dd3-11e7-84bc-b76f3e180b34.png)

### Web Map Services

Also great to see WFS, WMS, TIMS, WMS-C and WMST OGC web services through [NREL GeoServer](http://mapservices.nrel.gov/web/).

## Renewable Energy Economic / Technical Potential

* [NREL GIS - Renewable Energy Technical Potential](http://www.nrel.gov/gis/re_potential.html)

  ![](http://www.nrel.gov/gis/images/graphic_re_econ_potent_t.jpg)

* [NREL GIS - Renewable Energy Economic Potential](http://www.nrel.gov/gis/re_econ_potential.html)
  ![](http://www.nrel.gov/gis/images/graphic_re_potential_t.jpg)

**Comment by lkilcher** [comment]
@bbest I've inquired on why the MHK Atlas is not working. I'll let you know when it's fixed. I do have resource data for wave and tidal, but I'm hoping we can just grab it from the MHK Atlas when that is back online. Also, I'm not sure what you mean by 'GIS-friendly'. I assume this means public--at a minimum--but does it also mean: shapefile, or CSV, or SQL database of some kind, or ?

@pbeiter can confirm whether the OSW data listed above is the most up to date available.

**Comment by lkilcher** [comment]
@bbest 

OK. The [MHK Atlas](https://maps.nrel.gov/mhk-atlas/) is back online; sorry about that. You can download the wave data through that portal (click the down-arrow next to the layer).

The tidal data is too big to download through that interface, and I don't think it is currently publicly available anywhere else. I'll work on getting you a public link.

**Comment by bbest** [comment]
Great, thanks @lkilcher! The [MHK Atlas](https://maps.nrel.gov/mhk-atlas/) looks good. 

## Wave Power Density

![image](https://cloud.githubusercontent.com/assets/2837257/24884570/db75f036-1dfe-11e7-8c0f-09322b84c5d0.png)

The "?" popup continues:

> For complete details regarding this study please read the full report, available here:
[Mapping and Assessment of the United States Ocean Wave Energy Resource](http://en.openei.org/datasets/node/884).

This link (http://en.openei.org/datasets/node/884)) however redirects to only to the generic catalog (http://en.openei.org/datasets/dataset), but is presumably meant to go to:

* [NREL Wave Energy Assessment for the United States and Puerto Rico - Datasets - OpenEI Datasets](http://en.openei.org/datasets/dataset/nrel-wave-energy-assessment-for-the-us)

which is preferable in having data files over the duplicative pdf report only "dataset":

* [Mapping and Assessment of the United States Ocean Wave Energy Resource - Datasets - OpenEI Datasets](http://en.openei.org/datasets/dataset/mapping-and-assessment-of-the-united-states-ocean-wave-energy-resource)

The shapefile download from here is the same as the table I previously listed from the [NREL GIS  - Marine & Hydrokinetic Data](nrel.gov/gis/data_mhk.html) page:

Coverage | Zipped Shapefiles | Last Updated | Metadata
----------|--------------------|--------------|----------
Wave Power Density | [Zip 3.4 MB](http://en.openei.org/datasets/files/868/pub/wave_power_density.zip) | 10/20/2011 | [Wave Power Density.xml]

Yes, by "GIS-friendly" I meant something mappable (shapefile, KML, CSV, geodatabase, etc) vs an image (without georeferencing or value attribute table) or pdf that are found elsewhere on NREL.

## Tidal Power Density

Yep, I see the disclaimer:

> Annual Tidal Power Density
Downloading the entire dataset through the map interface is not possible due to size restrictions.

![image](https://cloud.githubusercontent.com/assets/2837257/24884808/0677e45a-1e00-11e7-8d9a-96d78de7f74e.png)

Thanks for looking into downloadable, public version.

**Comment by lkilcher** [comment]
> The "?" popup continues:

Hmmm... I don't have that problem on Chrome. 

> This link (http://en.openei.org/datasets/node/884)) however redirects to only to the generic catalog (http://en.openei.org/datasets/dataset), but is presumably meant to go to:

Where did you find the [node/884](http://en.openei.org/datasets/node/884) link?

**Comment by bbest** [comment]
Hi @lkilcher, 

Super minor, but probably good and easy to fix. Here's how I got there:

1. Visit https://maps.nrel.gov/mhk-atlas

1. In Data Layers, expand Marine & Hdyrokinetic Atlas > **Wave Power Density** > **WEF Annual** (one of the default layers checked on), and click on the "**?**" icon to the right of the layer, which gives you the following text:

    > **Wave Power Density**
    > Wave power density is the calculated kilowatts per meter of wave crest width at any given water depth. Equation A-6 of Appendix A in the full report.
    > 
    > **Source**:The Wave Energy Resource Assessment project is a joint venture between NREL, EPRI, and Virginia Tech. EPRI is the prime contractor, Virginia Tech is responsible for development of the models and estimating the wave resource, and NREL serves as an independent validator and also develops the final GIS-based display of the data.
    > 
    > For complete details regarding this study please read the full report, available here:
[Mapping and Assessment of the United States Ocean Wave Energy Resource](http://en.openei.org/datasets/node/884)
    > 
    > **Temporal Info**: February 2005 - July 2009
    > **Bathymetric Impacts on Resource Assessment**
    > Bathymetric effects...

1. The link for the text [Mapping and Assessment of the United States Ocean Wave Energy Resource](http://en.openei.org/datasets/node/884) is http://en.openei.org/datasets/node/884.

Hopefully that clears up this from previous...
